"""Add fcm_token to User model and report fields

Revision ID: 0842a785009d
Revises: 4f7332ab6efb
Create Date: 2025-10-06 18:29:00.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0842a785009d'
down_revision = '4f7332ab6efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported_org_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('donation_offer_id', sa.Integer(), nullable=True))
        # Explicitly naming the constraints to fix the error
        batch_op.create_foreign_key('fk_reports_reported_org_id_organizations', 'organizations', ['reported_org_id'], ['org_id'])
        batch_op.create_foreign_key('fk_reports_donation_offer_id_donation_offers', 'donation_offers', ['donation_offer_id'], ['offer_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fcm_token')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        # Dropping the named constraints
        batch_op.drop_constraint('fk_reports_donation_offer_id_donation_offers', type_='foreignkey')
        batch_op.drop_constraint('fk_reports_reported_org_id_organizations', type_='foreignkey')
        batch_op.drop_column('donation_offer_id')
        batch_op.drop_column('reported_org_id')

    # ### end Alembic commands ###