"""Add pickup_retries to DonationOffer

Revision ID: 110521b06822
Revises: 5fb0f378ae29
Create Date: 2025-09-30 17:17:48.964030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110521b06822'
down_revision = '5fb0f378ae29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_retries', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_offers', schema=None) as batch_op:
        batch_op.drop_column('pickup_retries')

    # ### end Alembic commands ###
