"""Add sub_category to Item model

Revision ID: 1159c9d38d4d
Revises: dcaf4f86ab99
Create Date: 2025-10-21 19:48:07.758604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1159c9d38d4d'
down_revision = 'dcaf4f86ab99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_category', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_items_sub_category'), ['sub_category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_sub_category'))
        batch_op.drop_column('sub_category')

    # ### end Alembic commands ###
