"""Add audio_url to chat messages

Revision ID: 143139fd25ca
Revises: c2337664f53c
Create Date: 2025-09-29 20:03:45.365587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143139fd25ca'
down_revision = 'c2337664f53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('audio_url')

    # ### end Alembic commands ###
