"""Add soft delete for messages

Revision ID: 17337c6d754c
Revises: 24696aa2e12f
Create Date: 2025-09-29 21:21:31.515688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17337c6d754c'
down_revision = '24696aa2e12f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
