"""Add DealProposal table and item finalization date

Revision ID: 2035bdcb1c48
Revises: c41789cc5f24
Create Date: 2025-09-29 19:23:40.364411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2035bdcb1c48'
down_revision = 'c41789cc5f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deal_finalized_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('deal_finalized_at')

    # ### end Alembic commands ###
