"""Remove audio_url from chat messages

Revision ID: 24696aa2e12f
Revises: 143139fd25ca
Create Date: 2025-09-29 21:12:00.772330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24696aa2e12f'
down_revision = '143139fd25ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('audio_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
