"""Add multiple categories to needs and category to offers

Revision ID: 3421c80f8c8f
Revises: dad82f24bc5e
Create Date: 2025-09-30 14:07:18.990371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3421c80f8c8f'
down_revision = 'dad82f24bc5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_disaster_needs')
    with op.batch_alter_table('disaster_needs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.Text(), nullable=True))
        batch_op.drop_column('category')

    with op.batch_alter_table('offered_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offered_items', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('disaster_needs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('categories')

    op.create_table('_alembic_tmp_disaster_needs',
    sa.Column('need_id', sa.INTEGER(), nullable=False),
    sa.Column('org_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('posted_at', sa.DATETIME(), nullable=True),
    sa.Column('categories', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('need_id')
    )
    # ### end Alembic commands ###
