"""Add status to DisasterNeed model

Revision ID: 3bf6ee43468d
Revises: f77bccf4ef74
Create Date: 2025-10-24 13:36:52.130543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf6ee43468d'
down_revision = 'f77bccf4ef74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disaster_needs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_disaster_needs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disaster_needs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disaster_needs_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
