"""Add sub_category exp to Item model

Revision ID: 487d72fd8601
Revises: 1159c9d38d4d
Create Date: 2025-10-21 20:40:04.131196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487d72fd8601'
down_revision = '1159c9d38d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_return_category', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('expected_return_sub_category', sa.String(length=255), nullable=True))
        batch_op.drop_column('expected_return')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_return', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('expected_return_sub_category')
        batch_op.drop_column('expected_return_category')

    # ### end Alembic commands ###
