"""add notification

Revision ID: 4f7332ab6efb
Revises: 110521b06822
Create Date: 2025-09-30 21:30:53.847613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7332ab6efb'
down_revision = '110521b06822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        # Add a unique and descriptive name for the foreign key constraint
        batch_op.create_foreign_key('fk_notifications_item_id_items', 'items', ['item_id'], ['item_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        # Use the same name to drop the constraint
        batch_op.drop_constraint('fk_notifications_item_id_items', type_='foreignkey')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###