"""add title to disaster needs

Revision ID: 5fb0f378ae29
Revises: 3421c80f8c8f
Create Date: 2025-09-30 14:39:38.630028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb0f378ae29'
down_revision = '3421c80f8c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disaster_needs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disaster_needs', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
