"""Make DealProposal.chat_session_id nullable

Revision ID: 845fa1add1ee
Revises: b49c6ffb223d
Create Date: 2025-10-20 20:33:03.786277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845fa1add1ee'
down_revision = 'b49c6ffb223d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_proposals', schema=None) as batch_op:
        batch_op.alter_column('chat_session_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_proposals', schema=None) as batch_op:
        batch_op.alter_column('chat_session_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
