"""Add offer delete

Revision ID: a8abe5cb1f5e
Revises: f77bccf4ef74
Create Date: 2025-10-22 14:29:29.532509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8abe5cb1f5e'
down_revision = 'f77bccf4ef74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_offers', schema=None) as batch_op:
        batch_op.alter_column('need_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'disaster_needs', ['need_id'], ['need_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_offers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'disaster_needs', ['need_id'], ['need_id'])
        batch_op.alter_column('need_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
