"""Add org bookmark capability

Revision ID: b49c6ffb223d
Revises: a02018e64d6d
Create Date: 2025-10-20 14:01:01.584651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49c6ffb223d'
down_revision = 'a02018e64d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_bookmarks_org_id'), ['org_id'], unique=False)
        
        # ADD constraint_name to unique constraint
        batch_op.create_unique_constraint(
            constraint_name='uq_org_item_bookmark', # ADDED NAME
            columns=['org_id', 'item_id']
        )
        
        # ADD check constraint with name
        batch_op.create_check_constraint(
            constraint_name='chk_bookmark_owner_type', # ADDED NAME
            condition='(user_id IS NOT NULL AND org_id IS NULL) OR (user_id IS NULL AND org_id IS NOT NULL)'
        )
        
        # ADD name to foreign key (optional but good practice)
        batch_op.create_foreign_key(
            constraint_name='fk_bookmarks_org_id_organizations', # ADDED NAME
            referent_table='organizations',
            local_cols=['org_id'],
            remote_cols=['org_id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        # Use constraint names for dropping
        batch_op.drop_constraint('fk_bookmarks_org_id_organizations', type_='foreignkey') # USE NAME
        batch_op.drop_constraint('chk_bookmark_owner_type', type_='check') # ADDED DROP
        batch_op.drop_constraint('uq_org_item_bookmark', type_='unique') # USE NAME
        
        batch_op.drop_index(batch_op.f('ix_bookmarks_org_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False) # Revert nullable change
        batch_op.drop_column('org_id')

    # ### end Alembic commands ###