"""Initial migration

Revision ID: c41789cc5f24
Revises: 7e739224af06
Create Date: 2025-09-29 18:22:00.931809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41789cc5f24'
down_revision = '7e739224af06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_session_id', sa.Integer(), nullable=True))
        # This has the correct name
        batch_op.create_foreign_key("fk_reports_chat_session_id", 'chat_sessions', ['chat_session_id'], ['session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        # This ALSO has the correct name
        batch_op.drop_constraint("fk_reports_chat_session_id", type_='foreignkey')
        batch_op.drop_column('chat_session_id')

    # ### end Alembic commands ###