"""Refactor chat schema for org-user

Revision ID: cac31169a97e
Revises: 8f78cbf2a047
Create Date: 2025-10-17 18:15:21.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac31169a97e'
down_revision = '8f78cbf2a047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_type', sa.String(length=50), nullable=False, server_default='user'))
        # In SQLite, we can't easily drop foreign keys, so we recreate the table.
        # This is a common pattern with Alembic and SQLite.

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('other_user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_chat_sessions_user1_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_chat_sessions_user2_id_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_chat_sessions_user_id_users', 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key('fk_chat_sessions_org_id_organizations', 'organizations', ['org_id'], ['org_id'])
        batch_op.create_foreign_key('fk_chat_sessions_other_user_id_users', 'users', ['other_user_id'], ['user_id'])
        batch_op.drop_column('user1_id')
        batch_op.drop_column('user2_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user2_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('user1_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_chat_sessions_other_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_chat_sessions_org_id_organizations', type_='foreignkey')
        batch_op.drop_constraint('fk_chat_sessions_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_chat_sessions_user2_id_users', 'users', ['user2_id'], ['user_id'])
        batch_op.create_foreign_key('fk_chat_sessions_user1_id_users', 'users', ['user1_id'], ['user_id'])
        batch_op.drop_column('other_user_id')
        batch_op.drop_column('org_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('sender_type')

    # ### end Alembic commands ###