"""Allow null item_offered_id in TradeRequest

Revision ID: dcaf4f86ab99
Revises: 845fa1add1ee
Create Date: 2025-10-21 18:24:03.325132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcaf4f86ab99'
down_revision = '845fa1add1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_proposals', schema=None) as batch_op:
        batch_op.alter_column('chat_session_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('trade_requests', schema=None) as batch_op:
        batch_op.alter_column('item_offered_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_requests', schema=None) as batch_op:
        batch_op.alter_column('item_offered_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('deal_proposals', schema=None) as batch_op:
        batch_op.alter_column('chat_session_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
