"""removed org verification log

Revision ID: e9c78c1ccb30
Revises: 0842a785009d
Create Date: 2025-10-06 20:26:46.760947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c78c1ccb30'
down_revision = '0842a785009d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_verification_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_verification_logs',
    sa.Column('log_id', sa.INTEGER(), nullable=False),
    sa.Column('org_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('verified_at', sa.DATETIME(), nullable=True),
    sa.Column('remarks', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###
