"""Add passive_deletes and ON DELETE SET NULL to chat_session donation_offer fk

Revision ID: f77bccf4ef74
Revises: d66c6ec76b68
Create Date: 2025-10-22 13:32:27.477725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77bccf4ef74'
down_revision = 'd66c6ec76b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chat_sessions_donation_offer_id'), type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_chat_sessions_donation_offer_id', # <<< ADD A CONSTRAINT NAME
            'donation_offers',
            ['donation_offer_id'], ['offer_id'],
            ondelete='SET NULL' # <<< REMOVE passive_deletes=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_chat_sessions_donation_offer_id'), 'donation_offers', ['donation_offer_id'], ['offer_id'])

    # ### end Alembic commands ###
